### ISSUE TITLE
Make app PWA

### ISSUE THREAD

**Issue by bolah2009** [adejam/react-calculator#6]
# Make app PWA

Can we make the app a [PWA](https://web.dev/progressive-web-apps/)?

This app seems to be a good fit for this feature, by doing this, you can open the app and do calculations without been connected to the internet.

Few things to make this work
- Add a manifest.json file
- Add all necessary icon sets and config to the manifest.json file
- Integrate the service worker with your react app

MDN has a great resource for this, kindly check out [the doc here](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps).

Please note that this is not a bug fix but a feature, so please do it only when you have the time. Good luck!

**Comment by adejam** [comment]
Thanks for the issue and the doc. I'll work on this as soon as I can.

**Comment by adejam** [comment]
I have made the App a PWA. This can be found on PR #7
